---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
setwd('/Users/micha/repos/march-madness/exports/2023')
conference = read.csv('conference.csv', header=TRUE, stringsAsFactors=FALSE)
scoreTmp = read.csv('score.csv', header=TRUE, stringsAsFactors=FALSE) 
bracket = read.csv('bracket.csv', header=TRUE, stringsAsFactors=FALSE)

BLOWOUT_CAP = 1000

teams = conference %>% pull(team)

scoreConferenceTeams = scoreTmp %>% 
  filter(team1 %in% teams) %>% 
  filter(team2 %in% teams)

scoreFlipped <- data.frame(
  year=scoreConferenceTeams$year,
  team1=scoreConferenceTeams$team2,
  team1_score=scoreConferenceTeams$team2_score,
  team2=scoreConferenceTeams$team1,
  team2_score=scoreConferenceTeams$team1_score
)

score <- rbind(scoreFlipped, scoreConferenceTeams)

#We need a "%!in%" operation for later on
"%!in%" <- function(x,table) match(x,table, nomatch = 0) == 0

#A team's conference
getConference = function(teamName) {
  conference %>% 
    filter(team == teamName) %>% 
    pull(conference) %>% 
    first
  
}

#All teams in a conference
teamsInConference = function(conferenceName) {
  conference %>% 
    filter(conference == conferenceName) %>% 
    pull(team)
}

#Games against a same-conference opponent
inConferenceGames = function(teamName) {
	conferenceTeams = teamsInConference(getConference(teamName))	
	score %>% 
	  filter(team1 == teamName) %>% 
	  filter(team2 %in% conferenceTeams)
}

#Get capped diff
#This softens the effects of enormous blowouts against weak teams by capping the max diff
getCappedDiff = function(score1, score2) {
  diff = score1 - score2
  ifelse(diff > BLOWOUT_CAP, BLOWOUT_CAP, diff)
}

#Median scoring differential when playing an in-conference opponent
medianInConferenceDiff = function(teamName) { 
  diffs = inConferenceGames(teamName) %>% 
    mutate(diff = getCappedDiff(team1_score, team2_score)) %>% 
    pull(diff) 
  median_diff = median(diffs)
  if (is.na(median_diff)) {
    return(0)
  } else {
    return(median_diff)
  }
}

#Teams in the bracket
getBracketTeams  = function() {
  bracket %>% 
    pull(team)
}

#Games against the bracket teams
#Exclude bracket teams in conference because we want to get a sense of how the
#team plays against good teams outside the conference
conferenceBracketGames = function(teamName) {
  score %>% 
    filter(team1 %in% teamsInConference(getConference(teamName))) %>% 
    filter(team2 %in% getBracketTeams()) %>% 
    filter(team2 %!in% teamsInConference(getConference(teamName)))
}  

#Games against opponents outside of the conference
outConferenceGames = function(teamName) {
	score %>% 
	  filter(team1 %in% teamsInConference(getConference(teamName))) %>% 
    filter(team2 %!in% teamsInConference(getConference(teamName)))
} 

#Median scoring differential for a conference when playing a tournament team
medianConferenceDiff = function(teamName) { 
  diffs = conferenceBracketGames(teamName) %>% 
    mutate(diff = getCappedDiff(team1_score, team2_score)) %>% 
    pull(diff) 
  median(diffs)
}

#Spread for one opponent
getSpread = function(teamName) {
  confDiff = medianConferenceDiff(teamName)
  inConfDiff = medianInConferenceDiff(teamName)
  confDiff + inConfDiff
}
 
#Letter grade for performance scores
getGrade = function(performance_score, spread) {
  ifelse(performance_score >= 20, 'A+',
  ifelse(performance_score >= 15, 'A',
  ifelse(performance_score >= 10, 'A-',
  ifelse(performance_score >= 5, 'B+',
  ifelse(performance_score >= 0, 'B',
  ifelse(performance_score >= -5, 'B',
  ifelse(performance_score >= -10, 'C+',
  ifelse(performance_score >= -15, 'C',
  ifelse(performance_score >= -20, 'C-',
  ifelse(performance_score >= -25, 'D+',
  ifelse(performance_score >= -30, 'D',
  ifelse(performance_score >= -35, 'D-', 'F'))))))))))))
}


mutateApproxAdjustedDiff = function(score) {
  spreads = data.frame(
    team = conference$team,
    spread = conference %>%  
      pull(team) %>% 
      lapply(getSpread) %>% 
      unlist
  )
  
  left_join(score, spreads, by = c('team2' = 'team')) %>% 
    mutate(diff = team1_score - team2_score) %>%
    mutate(capped_diff = getCappedDiff(team1_score, team2_score)) %>% 
    mutate(adjusted = capped_diff + spread)
}


mutatePreciseAdjustedDiff = function(adjusted) {
  precise_spreads = adjusted %>% 
      group_by(team1) %>% 
      summarize(precise_spread = median(adjusted)) %>% 
      rename(team = team1)
  
  left_join(adjusted, precise_spreads, by = c('team2' = 'team')) %>% 
    mutate(adjusted2 = getCappedDiff(team1_score, team2_score) + precise_spread)
}

mutatePerformanceScore = function(adjusted2) {
  precise_spreads2 = adjusted2 %>% 
      group_by(team1) %>% 
      summarize(precise_spread2 = median(adjusted2)) %>% 
      rename(team = team1)
  
  left_join(adjusted2, precise_spreads2, by = c('team2' = 'team')) %>% 
    mutate(performance_score = getCappedDiff(team1_score, team2_score) + precise_spread2) %>%
    mutate(grade = getGrade(performance_score))
}

performance = score %>% 
    mutateApproxAdjustedDiff %>% 
    mutatePreciseAdjustedDiff %>%
    mutatePerformanceScore

```

```{r}
setwd('/Users/micha/repos/march-madness/exports/2023')
write.table(performance, file = "performance.csv", sep = ",",
            row.names = TRUE, col.names = NA)
```

```{r}
performance
```


```{r}

simulate = function(team1_name, team2_name) {
  num_trials = 10000
  team1_scores = performance %>% 
    filter(team1 == team1_name) %>% 
    pull(performance_score)
  team2_scores = performance %>% 
    filter(team1 == team2_name) %>% 
    pull(performance_score)
  team1_wins = 0
  team2_wins = 0

  for(i in 1:num_trials) {
    team1_score = sample(team1_scores, 1, replace=TRUE)
    team2_score = sample(team2_scores, 1, replace=TRUE)
    if(team1_score > team2_score) {
      team1_wins = team1_wins + 1
    } else if(team2_score > team1_score) {
      team2_wins = team2_wins + 1
    }
  }
  
  print('----------------------------')
  print('WINNING PERCENTAGE')
  print('----------------------------')
  print(paste(team1_name, team1_wins / num_trials))
  print(paste(team2_name, team2_wins / num_trials))
  print('----------------------------')
  print('PERFORMANCE SCORE')
  print('----------------------------')
  print(paste(team1_name, median(team1_scores)))
  print(paste(team2_name, median(team2_scores)))
}

```

```{r}

getChampionshipScore = function(team1_name, team2_name) {
  t1_score = performance %>% 
    filter(team1 == team1_name) %>% 
    pull(team1_score) %>% 
    median
  
  t1_allowed = performance %>% 
    filter(team1 == team1_name) %>% 
    pull(team2_score) %>% 
    median
  
  t2_score = performance %>% 
    filter(team1 == team2_name) %>% 
    pull(team1_score) %>% 
    median
  
  t2_allowed = performance %>% 
    filter(team1 == team2_name) %>% 
    pull(team2_score) %>% 
    median
  
  print(paste((t1_score + t2_allowed) / 2, (t2_score + t1_allowed) / 2, sep = ' - '))
}


```

```{r}
simulate('Arizona', 'Seton Hall')
getChampionshipScore('Gonzaga', 'Auburn')
```

